### ISSUE TITLE
Unable to control the light

### ISSUE THREAD

**Issue by ITensEI** [roslovets/SP110E-HASS#8]
Integration adds the light and it's features, but unable to control it. When toggling switch on it turns off without any changes to the light. No errors that I could see in the logs.

**Comment by roslovets** [comment]
Hi, try to enable strict mode in config and you will see errors in log

**Comment by ITensEI** [comment]
Thank you! Now at least I see an error! I'm getting the following

```
Update for light.bedstrip fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sp110e/controller.py", line 208, in _connect_with_retries
    await self._driver.connect(self._mac, timeout=self._timeout)
  File "/usr/local/lib/python3.10/site-packages/sp110e/driver.py", line 42, in connect
    device = await BleakScanner.find_device_by_address(mac_address, timeout=timeout)
AttributeError: type object 'HaBleakScannerWrapper' has no attribute 'find_device_by_address'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/config/custom_components/sp110e/light.py", line 220, in async_update
    self._handle_exception(exception)
  File "/config/custom_components/sp110e/light.py", line 246, in _handle_exception
    raise exception
  File "/config/custom_components/sp110e/light.py", line 217, in async_update
    await self._device.update()
  File "/usr/local/lib/python3.10/site-packages/sp110e/controller.py", line 60, in update
    await self._connect_with_retries()
  File "/usr/local/lib/python3.10/site-packages/sp110e/controller.py", line 211, in _connect_with_retries
    raise Exception
Exception
```

**Comment by roslovets** [comment]
Hm, is it problem with Bleak version?
Unfortunately I don't have access to my HASS to test it.

**Comment by Poaser** [comment]
get the same error

**Comment by evadim** [comment]
And one more with this issue.
