### ISSUE TITLE
This integration is not working...

### ISSUE THREAD

**Issue by danielbrunt57** [roslovets/SP110E-HASS#9]
The SP110E is working fine with the LED Hue app on my phone.
```
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/sp110e/light.py:217
Integration: sp110e (documentation, issues)
First occurred: 8:36:19 PM (1 occurrences)
Last logged: 8:36:19 PM

Update for light.sp110e fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sp110e/controller.py", line 208, in _connect_with_retries
    await self._driver.connect(self._mac, timeout=self._timeout)
  File "/usr/local/lib/python3.10/site-packages/sp110e/driver.py", line 42, in connect
    device = await BleakScanner.find_device_by_address(mac_address, timeout=timeout)
AttributeError: type object 'HaBleakScannerWrapper' has no attribute 'find_device_by_address'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 548, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_device_update
    raise exc
  File "/config/custom_components/sp110e/light.py", line 220, in async_update
    self._handle_exception(exception)
  File "/config/custom_components/sp110e/light.py", line 246, in _handle_exception
    raise exception
  File "/config/custom_components/sp110e/light.py", line 217, in async_update
    await self._device.update()
  File "/usr/local/lib/python3.10/site-packages/sp110e/controller.py", line 60, in update
    await self._connect_with_retries()
  File "/usr/local/lib/python3.10/site-packages/sp110e/controller.py", line 211, in _connect_with_retries
    raise Exception
Exception
```
```
  - platform: sp110e
    mac: 37:73:03:2a:37:82 # Replace with your MAC address (required)
    name: SP110E
    sequence: BRG
    pixels: 10
    strict: true
```
![image](https://user-images.githubusercontent.com/49846893/219550880-bfc8450d-a2ef-4d01-aa04-5be4e6ec5955.png)

![image](https://user-images.githubusercontent.com/49846893/219551016-aec635d4-147c-4567-a7fa-ec32b4e13482.png)

```
  "data": {
    "manager": {
      "adapters": {
        "hci0": {
          "address": "00:1A:7D:DA:71:07",
          "sw_version": "homeassistant",
          "hw_version": "usb:v1D6Bp0246d053F",
          "passive_scan": true,
          "manufacturer": "cyber-blue(HK)Ltd",
          "product": "CSR8510 A10",
          "vendor_id": "0a12",
          "product_id": "0001"
        }
      },
```

**Comment by lyn1337** [comment]
Seems to be my problem, too. Any update?

**Comment by bordeux** [comment]
Started using Universal Light Controller from hass. With this integration it works like it should

**Comment by danielbrunt57** [comment]
> Started using Universal Light Controller from hass. With this integration it works like it should

Thanks for the heads up!  It works great!

**Comment by evadim** [comment]
For me only Universal Light Controller v2 (beta) works.

**Comment by zauberflute** [comment]
Came here to log this error - I get the same thing. HA updated Bluez version recently, apparently there are changes to the function calls.
